# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AS2PEDEEHxQV5pkz36ZHnIGAOdta3UrB
"""

def triangleCanBeConstructed(a, b, c):
  if ((a+b) > c) & ((a+b)>c) & ((b+c)>a):
    return True
  else:
    return False